[[plugins]]
package = "netlify-plugin-no-more-404"

  # all inputs are optional, we just show you the defaults below
  [plugins.inputs]
  
  # either "warn" or "error"
  on404 = "error" 
  
  # (for development) turn true for extra diagnostic logging
  debugMode = true

[[redirects]]
  from = "/Sourdough-Calculator"
  to = "sourdough.emilybonar.com"
  status = 200
  force = true